### ISSUE TITLE
Event listener

### ISSUE THREAD

**Issue by fank** [catgiggle/OctoPrint-GpioControl#21]
An ability to define "events" like enable while printing for given GPIOs.

Example: I would like to enable the "chassis fan" every time a print is running.

![image](https://user-images.githubusercontent.com/1900106/110516850-650dee80-810a-11eb-9e1b-d7f856f66e5a.png)

**Comment by catgiggle** [comment]
It's very good idea. Thanks! I'm planning to implement something like this in a more advanced version of this plugin. This is because I want to keep GPIO Control as simple as possible. Please see https://github.com/catgiggle/OctoPrint-GpioControl/discussions/17 for more details and feel free to add any other ideas :)
